language: swift

osx_image: xcode9.1
xcode_workspace: PlayerControls
xcode_scheme: Demo
xcode_sdk: iphonesimulator11.1


branches:
 only:
 - travis

before_install:
- brew update
- brew install sourcery
- brew install carthage
- cd Demo
- carthage update --platform iOS
- cd ..
- brew cask install fastlane

script: fastlane verify
